wandb_version: 1

input_dim:
  desc: null
  value: 3
neuron:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0002
batch_size:
  desc: null
  value: 512
num_epochs:
  desc: null
  value: 2000
patience:
  desc: null
  value: 10
scaler:
  desc: null
  value: MinMaxScaler
optimizer:
  desc: null
  value: Adam
loss_function:
  desc: null
  value: MSELoss
data_file:
  desc: null
  value: energy_surface_1_1.txt
process_param_l:
  desc: null
  value: 1.4
unit_conversion:
  desc: null
  value: au_to_eV
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731572412
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.17.9
      8:
      - 3
      - 5
      13: windows-amd64
